services:

  db:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123!

  app:
    image: hung-java-app
    build:
      context: ./ASM
      dockerfile: Dockerfile
    ports:
      - "8089:8888"
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://db:1433;databaseName=LENUP;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourPassword123!
    depends_on:
      - db

volumes:
  mssql_data:
